postgresql: &postgresql
  adapter: postgresql
  database: cwdg_<%= Rails.env %>
  encoding: unicode
  min_messages: ERROR
  username: postgres
  password:

defaults: &defaults
  host: localhost
  pool: 5
  timeout: 5000
  <<: *<%= ENV['DB'] || "postgresql" %>

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
