postgresql: &postgresql
adapter: postgresql
encoding: unicode
min_messages: ERROR

defaults: &defaults
  host: localhost
  timeout: 5000
  pool: 5
  <<: *<%= ENV['DB'] || "postgresql" %>

development:
  <<: *defaults
  database: cwdg_development

test:
  <<: *defaults
  database: cwdg_test
