# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.
defaults: &default
  # Generate your own https://github.com/settings/applications/new
  # and put them into your .env file
  github_client_id:             <%= ENV["GITHUB_CLIENT_ID"]        %>
  github_client_secret:         <%= ENV["GITHUB_CLIENT_SECRET"]    %>
  # Create a new app at https://apps.twitter.com/app/new
  # and put your keys in your .env file
  twitter_consumer_key:         <%= ENV["TWITTER_CONSUMER_KEY"]    %>
  twitter_consumer_secret:      <%= ENV["TWITTER_CONSUMER_SECRET"] %>
  twitter_access_token:         <%= ENV["TWITTER_ACCESS_TOKEN"]    %>
  twitter_access_token_secret:  <%= ENV["TWITTER_ACCESS_TOKEN_SECRET"]    %>

development:
  <<: *default
  secret_key_base: 44c6dc82806e70370e9ffbb5c14421143ec480ec4ff1e3e8eaa3aa77342a38f7a9c9940015b9f99d289f32fa62e1f90a71aff9960ab80291d05d9d22e776b0db

test:
  <<: *default
  secret_key_base: 9c2db612a2d21240feb514cf2219d51bc2b1334cee5f16a58d15f04b8ed2be07352e43c7fafd228ca1152f9a072419fbe6edd2f11ed02dac3479f06e536bde32

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  <<: *default
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
