# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.
defaults: &default
  github_admin_token: <%= ENV["GITHUB_ADMIN_TOKEN"] %>
  github_key: <%= ENV["GITHUB_KEY"] %>
  github_secret: <%= ENV["GITHUB_SECRET"] %>

development:
  <<: *default
  secret_key_base: <%= ENV["DEVELOPMENT_SECRET_KEY_BASE"] %>

test:
  <<: *default
  secret_key_base: <%= ENV["TEST_SECRET_KEY_BASE"] %>

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  <<: *default
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
